-- Lynflow Supabase schema
-- Run this file in the Supabase SQL Editor before enabling the remote mode.

-- Required for gen_random_uuid() on hosted Supabase projects.
create extension if not exists pgcrypto;

-- Shared trigger function used by tables that keep updated_at.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Public profile data tied to Supabase Auth users.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Automatically creates a profile when a Supabase Auth user is created.
-- This keeps signup stable even when email confirmation is enabled.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, email)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data ->> 'name', ''),
      nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
      'Usuaria'
    ),
    coalesce(new.email, '')
  )
  on conflict (id) do update
  set
    name = excluded.name,
    email = excluded.email,
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- User-owned tasks. The front-end maps order_index to Task.order.
create table if not exists public.tasks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  category text not null default 'Geral',
  priority text not null check (priority in ('low', 'medium', 'high')),
  done boolean not null default false,
  due_date date,
  recurrence text not null default 'none' check (
    recurrence in ('none', 'daily', 'weekly', 'monthly')
  ),
  order_index integer not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Keep existing remote projects compatible when this schema is re-run.
alter table public.tasks
add column if not exists due_date date;

alter table public.tasks
add column if not exists recurrence text not null default 'none';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'tasks_recurrence_check'
      and conrelid = 'public.tasks'::regclass
  ) then
    alter table public.tasks
    add constraint tasks_recurrence_check
    check (recurrence in ('none', 'daily', 'weekly', 'monthly'));
  end if;
end;
$$;

-- User-owned activity feed generated by task operations.
create table if not exists public.task_activities (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (
    type in (
      'created',
      'completed',
      'reopened',
      'deleted',
      'reordered',
      'cleared',
      'reset'
    )
  ),
  title text not null,
  description text not null,
  created_at timestamptz default now()
);

-- User filters used by queries, policies and realtime refreshes.
create index if not exists profiles_id_idx on public.profiles (id);
create index if not exists tasks_user_id_idx on public.tasks (user_id);
create index if not exists task_activities_user_id_idx on public.task_activities (user_id);

-- Keep updated_at fresh on mutable tables.
drop trigger if exists profiles_set_updated_at on public.profiles;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists tasks_set_updated_at on public.tasks;

create trigger tasks_set_updated_at
before update on public.tasks
for each row execute function public.set_updated_at();

-- Register task tables in Supabase Realtime when the hosted publication exists.
-- The checks keep this block safe to re-run in existing projects.
do $$
begin
  if exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) then
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'tasks'
    ) then
      alter publication supabase_realtime add table public.tasks;
    end if;

    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'task_activities'
    ) then
      alter publication supabase_realtime add table public.task_activities;
    end if;
  end if;
end;
$$;

-- Enable Row Level Security on every user-owned table.
alter table public.profiles enable row level security;
alter table public.tasks enable row level security;
alter table public.task_activities enable row level security;

alter table public.profiles force row level security;
alter table public.tasks force row level security;
alter table public.task_activities force row level security;

-- The anon role should not access user-owned tables without an authenticated JWT.
revoke all on public.profiles from anon;
revoke all on public.tasks from anon;
revoke all on public.task_activities from anon;

-- Profiles policies: each authenticated user manages only their own profile.
drop policy if exists "Users can select own profile" on public.profiles;

create policy "Users can select own profile"
on public.profiles for select
to authenticated
using (auth.uid() is not null and auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;

create policy "Users can insert own profile"
on public.profiles for insert
to authenticated
with check (auth.uid() is not null and auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;

create policy "Users can update own profile"
on public.profiles for update
to authenticated
using (auth.uid() is not null and auth.uid() = id)
with check (auth.uid() is not null and auth.uid() = id);

drop policy if exists "Users can delete own profile" on public.profiles;

create policy "Users can delete own profile"
on public.profiles for delete
to authenticated
using (auth.uid() is not null and auth.uid() = id);

-- Tasks policies: every task row must belong to the signed-in user.
drop policy if exists "Users can select own tasks" on public.tasks;

create policy "Users can select own tasks"
on public.tasks for select
to authenticated
using (auth.uid() is not null and auth.uid() = user_id);

drop policy if exists "Users can insert own tasks" on public.tasks;

create policy "Users can insert own tasks"
on public.tasks for insert
to authenticated
with check (auth.uid() is not null and auth.uid() = user_id);

drop policy if exists "Users can update own tasks" on public.tasks;

create policy "Users can update own tasks"
on public.tasks for update
to authenticated
using (auth.uid() is not null and auth.uid() = user_id)
with check (auth.uid() is not null and auth.uid() = user_id);

drop policy if exists "Users can delete own tasks" on public.tasks;

create policy "Users can delete own tasks"
on public.tasks for delete
to authenticated
using (auth.uid() is not null and auth.uid() = user_id);

-- Activity policies: each user can read, write, and clear only their own feed.
drop policy if exists "Users can select own task activities" on public.task_activities;

create policy "Users can select own task activities"
on public.task_activities for select
to authenticated
using (auth.uid() is not null and auth.uid() = user_id);

drop policy if exists "Users can insert own task activities" on public.task_activities;

create policy "Users can insert own task activities"
on public.task_activities for insert
to authenticated
with check (auth.uid() is not null and auth.uid() = user_id);

drop policy if exists "Users can update own task activities" on public.task_activities;

create policy "Users can update own task activities"
on public.task_activities for update
to authenticated
using (auth.uid() is not null and auth.uid() = user_id)
with check (auth.uid() is not null and auth.uid() = user_id);

drop policy if exists "Users can delete own task activities" on public.task_activities;

create policy "Users can delete own task activities"
on public.task_activities for delete
to authenticated
using (auth.uid() is not null and auth.uid() = user_id);
